using DotnetDiRulesAudit.Model;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace DotnetDiRulesAudit.Analysis;

public static class AnalysisHelpers
{
    public static SourceLocation? ToSourceLocation(this SyntaxNode node)
    {
        var span = node.SyntaxTree.GetLineSpan(node.Span);
        if (string.IsNullOrWhiteSpace(span.Path))
        {
            return null;
        }

        return new SourceLocation(span.Path, span.StartLinePosition.Line + 1, span.StartLinePosition.Character + 1);
    }

    public static bool IsGeneratedFile(SyntaxTree tree)
    {
        var path = tree.FilePath;
        if (path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase) ||
            path.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase) ||
            path.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase) ||
            path.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        var text = tree.GetText();
        var length = Math.Min(text.Length, 512);
        return text.ToString(TextSpan.FromBounds(0, length)).Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);
    }

    public static bool IsTestProject(Project project)
    {
        if (project.Name.Contains("Test", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return project.MetadataReferences.Any(r =>
            r.Display?.Contains("xunit", StringComparison.OrdinalIgnoreCase) == true ||
            r.Display?.Contains("nunit", StringComparison.OrdinalIgnoreCase) == true ||
            r.Display?.Contains("mstest", StringComparison.OrdinalIgnoreCase) == true);
    }

    public static ITypeSymbol? GetTypeOfExpression(SemanticModel model, ArgumentSyntax argument, CancellationToken cancellationToken)
    {
        if (argument.Expression is TypeOfExpressionSyntax typeOfExpression)
        {
            return model.GetTypeInfo(typeOfExpression.Type, cancellationToken).Type;
        }

        return null;
    }

    public static bool IsOpenGeneric(ITypeSymbol symbol)
    {
        return symbol is INamedTypeSymbol named && named.IsGenericType && named.TypeArguments.Any(t => t.TypeKind == TypeKind.TypeParameter);
    }
}
